wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/amzn-base.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/amzn-header.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/amzn-envelope.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Product.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ClothingAccessories.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProductClothing.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Miscellaneous.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/CameraPhoto.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Home.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Sports.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/HomeImprovement.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Tools.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FoodAndBeverages.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Gourmet.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Jewelry.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Health.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/CE.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Computers.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/SWVG.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Wireless.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Beauty.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Office.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/MusicalInstruments.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/AutoAccessory.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/PetSupplies.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ToysBaby.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/TiresAndWheels.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Music.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Video.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Lighting.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/LargeAppliances.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/CatPIL.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Customer.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FulfillmentCenter.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FulfillmentOrderCancellationRequest.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/FulfillmentOrderRequest.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Image.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Inventory.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Item.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Listings.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Loyalty.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/MultiChannelOrderReport.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/NavigationReport.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Offer.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderAcknowledgement.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderAdjustment.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderFulfillment.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderNotificationReport.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderReport.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Override.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Price.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProcessingReport.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProductImage.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Relationship.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ReverseFeed.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/SettlementReport.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Store.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/WebstoreItem.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/AttributeGroups.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/TypeDefinitions.xsd 
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ListingSummary.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/PaymentMethod.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/ProductAttributes.xsd
wget --no-check-certificate https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/CustomerAddress.xsd